#!/usr/bin/env zsh

if [[ -z xbacklight ]]; then
  output=$(xbacklight 2>&1)
  rc=$?
  
  if [ $output = "No outputs have backlight property" ]; then
    echo "N/A"
    exit 0
  fi
  
  echo "$(xbacklight | cut -d'.' -f1)%"
else
  echo "N/A"
fi
