#!/usr/bin/env zsh

output=$(acpi -b 2>&1)
if [ $output = "No support for device type: power_supply" ]; then
  echo "N/A"
  exit 0
fi

read var1 var2 < <(acpi -b | grep -o '[0-9]*%' | cut -d'%' -f1 | xargs echo)
perc=$((($var1 + $var2) / 2))%

if [[ -z $(acpi -b | grep Charging) ]]; then
  echo "Battery: $perc"
else
  echo "Charging: $perc"
fi

