#!/usr/bin/env zsh

ethname=$(ip a | grep -o "enp.*" | head -n 1)

if [ -z $ethname ]; then
  echo "no interface"
else
  # TODO: figure out color support
  #echo -e "\e[94m$(ip -d a show $ethname | grep inet6 | head -n1 | cut -d' ' -f6)\e[39m"
  addr=$(ip -d a show $ethname | grep inet | head -n1 | cut -d' ' -f6)
  if [ -z $addr ]; then
    echo "N/A"
  else
    echo $addr
  fi
fi


