#!/usr/bin/env zsh

output=$(acpi -b 2>&1)
if [ $output = "No support for device type: power_supply" ]; then
  echo "N/A"
  exit 0
fi

read var1 var2 < <(acpi -b | grep -o '[0-9]*%' | cut -d'%' -f1 | xargs echo >> /dev/null)
echo "$((($var1 + $var2) / 2))%"
