#!/usr/bin/env zsh

muted=$(pactl list sinks | grep Mute | cut -d' ' -f2)

if [[ $muted = "yes" ]]; then
  echo "Muted"
else
  pactl list sinks | grep 'Volume: front' | head -n1 | cut -d ' ' -f6 | grep -o "[0-9][0-9]%"
fi


