#!/usr/bin/env zsh

ethname=$(ip a | grep -o "enp.*" | head -n 1 | cut -d':' -f1)

if [ -z $ethname ]; then
  echo "\#ff0000"
else
  addr=$(ip -d a show $ethname | grep inet | head -n1 | cut -d' ' -f6)
  if [ -z $addr ]; then
    echo "\#ff0000"
  else
    echo "\#00ff00"
  fi
fi


