#!/usr/bin/env zsh

ethname=$(ip a | grep -o "enp.*" | head -n 1 | cut -d':' -f1)

if [ -z $ethname ]; then
  echo "no interface"
else
  addr=$(ip -d a show $ethname | grep inet | head -n1 | cut -d' ' -f6)
  if [ -z $addr ]; then
    echo "N/A"
  else
    echo $addr
  fi
fi


